### ISSUE TITLE
Problem with PanelDemo.py on Rpi3

### ISSUE THREAD

**Issue by ValDY69** [BNNorman/rpi-rgb-led-matrix-animator#1]
Hello ,

I really like your library , thank you for your work !

I clone your repo on my local windows 10 dev pc and install pycharm and anaconda2 and i can run perfeclty your differents examples and it works like a charm.

But on my Rpi3 (i am on the same wiring Active3 with 64*64 LEDpanels) with Raspbian jessie with python lib installed from Hzeller , i also installed berryconda for the dependencies.

I have the following error when trying to play your examples :  

"Traceback (most recent call last):
File "PanelDemo.py",line 50, in <module>
    videoName"./PanelDemo.avi")
File "/home/pi/libtest/LEDAnimator/Panel.py", line 144 , in init
    canvas=matrix.CreateFrameBuffer()
AttributeError: 'rgbmatrix.core.RGBMatrix' object has no attribute 'CreateFrameBuffer'
" 
it seems that there is no method "CreateFrameBuffer" in the rgbmatrix from hzeler.

i don't know what i have to do to debug this , Can you help me please ?

**Comment by BNNorman** [comment]
Many Thanks.

 

Looks like it might be an error in the hzeller driver installation.

 

Have you tried running his examples in bindings/python/samples? – they communicate directly with the drivers. If they don’t work my code will not be able to either. 

 

If that’s the case you need to talk to hzeller – he normally responds quickly. But first, how did you install it? 

 

The only part of my code that talks to the hzeller driver is Panel.py – it selects the simulator or the hzeller lib depending upon the platform it’s running on. It looks like its imported hzeller’s RGBMatrix otherwise you would have gotten an import error.

 

Regards

Brian

**Comment by ValDY69** [comment]
Thank you for your quick answer ,

i follow this step to install the library :

sudo apt-get update && sudo apt-get install python2.7-dev python-pillow -y
make build-python
sudo make install-python

but i have not tried yet the attached sample i will do this as soon as possible !

Regards ,
Valentin

**Comment by BNNorman** [comment]
I meant, how did you install the hzeller drivers? Git clone etc.

On 4 Feb 2018 9:39 pm, "ValDY69" <notifications@github.com> wrote:

Thank you for your quick answer ,

i follow this step to install the library :

sudo apt-get update && sudo apt-get install python2.7-dev python-pillow -y
make build-python
sudo make install-python

but i have not tried yet the attached sample i will do this as soon as
possible !

Regards ,
Valentin

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/BNNorman/rpi-rgb-led-matrix-animator/issues/1#issuecomment-362942145>,
or mute the thread

**Comment by ValDY69** [comment]
Yes i git clone his Repo and run a make
And test his exemples on my Led panel and  its work but not tried the exemples on the python binding directly

**Comment by BNNorman** [comment]
Did you run make install? Might need to sudo that.

**Comment by ValDY69** [comment]
I do the following after git clone :

make -C examples-api-use
sudo examples-api-use/demo -D0

And the exemple work on my panel .

After that i run this command for python binding :

sudo apt-get update && sudo apt-get install python2.7-dev python-pillow -y
make build-python
sudo make install-python

And i directly test your sample and i have the previous error 

But i have not run an make install 

I Will try this tomorrow ! Thank you

**Comment by BNNorman** [comment]
I found a typo in Panel.py which caused the problem.  I have updated it on Github.

 

Check /usr/local/lib/python2.7/dist-packages/rgbmatrix exists.  If not you need to cd into the python folder then run sudo make install.

**Comment by ValDY69** [comment]
Hello , thank you for the Fix !

I finally **succeeded to play your Examples** python script !!

but i have encountered some problems during test :

first : 

![image](https://user-images.githubusercontent.com/34503404/35806646-86e9ce60-0a80-11e8-8428-caa9de3c4e8b.png)

resolve by comment the "try except" : 

![bugfixdecorators](https://user-images.githubusercontent.com/34503404/35806691-b353e472-0a80-11e8-9714-24b8a91c101c.PNG)

Second : 

![allchainanimatorantialiasmissingnone](https://user-images.githubusercontent.com/34503404/35806734-d5a418da-0a80-11e8-9119-0d293c490079.PNG)

resolve by adding a default None parameters to the third arguments:

![image](https://user-images.githubusercontent.com/34503404/35806771-ee740348-0a80-11e8-85b2-8ff81b5e7660.png)

third : 

![image](https://user-images.githubusercontent.com/34503404/35806880-52e48e4c-0a81-11e8-8af0-01e6b57c9120.png)


resolve by replacing float value with int : 

![fiximgpanel](https://user-images.githubusercontent.com/34503404/35806922-763d789a-0a81-11e8-8276-f717bc3461cb.PNG)

Regards ,
Valentin

**Comment by BNNorman** [comment]
I’ve corrected that – you can download a new UtilLib.py or remove the import for Decorators – it’s code I used for timing tests when trying to speed up sections of code.

 

I’ll have a look at why the last decorator isn’t working.

**Comment by ValDY69** [comment]
ok nice !

i close this issue because it's working for me now !
thank you
