### ISSUE TITLE
Text Scrolling problem 

### ISSUE THREAD

**Issue by ValDY69** [BNNorman/rpi-rgb-led-matrix-animator#3]
Hello Brian ,

After several test on the TextDemo.py i don't find a way to scroll a text "entirely" : 

the text do not complety exit from the left side of the screen 

instead of that it's disappears when the end of the text reaches the right side of the screen 
(when the text is larger than the screen itself otherwise  it's disappears when the beginning of the text reaches the left side) 

it's a bit complicated to explain but the problem makes scrolling not smooth 

Regards ,
Valentin

**Comment by BNNorman** [comment]
First of all. The panels are low resolution. Slow update rates will always give a jerky effect.

 

Second, the issues are caused by a combination of FPS, animation speed and animation duration.

 

Animations are terminated abruptly when the duration is reached, so you need to adjust the speed and duration until you get it to work.

 

Third, the ability of the animator to keep “good time” depends on the time taken by each step of each animation. If they take longer than allowed by the FPS the animation will get out of step. I found, with other animations, using elapsed time is better at ensuring an animation completes before the duration has expired rather than ticks.

 

Fourth, text is first rendered as an image and the image is moved over the background. The size of the image can be obtained as is done in TextDemo.py like this

 

bdfText="Hello sweetie BDF 12pt text here!"

bdf=Font("BDF",12)

tLenBDF,h=bdf.getTextBbox(bdfText)

 

Make sure the endPos X value is at least –tLenBDF

 

You could add a fiddle factor in case the calculated length is slightly incorrect. For BDF fonts is done counting characters and multiplying by their widths. For HERSHEY the length is estimated by openCV routines (and may need a fudge factor adding)

 

Fifth, there’s always room for improvement – I’ll have a look later to see if I can improve that – or you could look at the code and try to do that yourself – all feedback gratefully accepted.

 

 

Best Regards

Brian

**Comment by ValDY69** [comment]
Thank you brian for your quick answer !

i understand that the panels are low resolution , no problem with that

i don't think that the duration is reached because i set it to 50.

I tried to increase the duration to your textDemo.py from 20 to 50 with the same speed 0.3 but i still have the same problem :  the scrolling don't go to the end of panels and disappears quicker , i also tried to increase the endPos but it still not work properly

can you give me the combinaison of parameters that i have to set with your sample : 

bdfSeq= AnimSequence([
    TextAnimations.Move (duration=50, speed=0.3, fps=FPS, startPos=(64,20), endPos=(-tLenBDF,20), text=bdfmsg,
                         multiColored=True, Xpos=32,Ypos=32,debug=DEBUG,id="BDFSEQ"),
]) 

Regards ,
Valentin

**Comment by ValDY69** [comment]
i found a solution that work for me i put some spaces at the end of string when i want that my text scroll completly out of the screen.

I will do some test to understand the possibilities of your animator process !

Regards ,
Valentin

**Comment by BNNorman** [comment]
Ok, that suggests that the calculation of the image size is not quite correct. Which font were you using (BDF or HERSHEY)?

 

By the way. Using Hershey you can also use anti-aliasing which may help the motion look smoother.

 

I will look into improving the code.

 

Regards

 

Brian.

**Comment by ValDY69** [comment]
I use BDF i have not try with Hershey 
i will try it as soon as possible 

I will look into improving the code.  -->  thank you brian

Regards ,
Valentin

**Comment by BNNorman** [comment]
There is a bug somewhere which causes the alphaBlend() routine in UtilLib.py to abandon blending because the image overlap areas are different  when the text image scrolls to the point the rightmost edge is within the Panel region. I’m guessing that’s why the text scroll halts at the end of the text.

 

At the moment it is a 1 pixel width difference – and it only appears to happen when the back end of a text image moves into the panel area. It may also happen with height – I’m guessing that when I find the cause of the width discrepancy it will tell me if height would also be affected. (similar calcs)

 

The alpha blending only works with images of the same shape. 

 

I’m trying to track it down.

 

BTW. With Hershey fonts if you include lineType=LINE_AA  in the text() parameter list it should give you anti-aliased text. Might look smoother when scrolling at low speed.

 

Regards

**Comment by BNNorman** [comment]
Yes, i did see that. The problem is in UtilLib.py getOverlapCoords().,
Which, oddly, appears to work for all other conditions. Im working on it

**Comment by BNNorman** [comment]
I’ve modified UtilLib.py – seems to be working ok. Text now scrolls all the way off the screen.

 

Added a new TextAnimation called MoveTimed. This uses the duration only (not speed) and is more user friendly. If you set the duration to 10 seconds – that’s how long it runs for, but it only runs once. 

 

I have modified TextDemo to use the new MoveTimed – but in doing so spotted a problem with Hershey fonts – letters missing off the end of the message.

 

Regards

Brian

**Comment by ValDY69** [comment]
Hello Brian ,
Thank you for your improvement , this is really what i was looking for !

i have seen no difference between the 2 fonts 

But the only problem that i see now is that when the text have completly scroll it begin another cycle during approximatively 1 sec before restart again normaly

i also see that this problem is linked with the duration (less duration reduce the bug)

for now i resolve this by adding a one space char before the begining of the text

Regards ,
Valentin

**Comment by BNNorman** [comment]
Were you using MoveTimed? It should run once only and not restart. (unless it's the only animation in a sequence.)

Hershey fonts. Did you add lineType=LINE_AA?

You should be able to put that in the Text parameter list

cv2msg=Text(text=cv2Text,fontSize=12,fontFace=FONT_HERSHEY_SIMPLEX,
                 fgColor=Palette.XMAS,bgColor=(125,0,125,255),lineType=LINE_AA)

OR in the animation sequence:-

cv2Seq= AnimSequence([
    TextAnimations.MoveTimed (duration=20, fps=FPS, startPos=(64,40), endPos=(-tLenCV2,40),
                         text=cv2msg, lineType=LINE_AA),

If the latter works but not the former I need to add some code to let it be done either way though I think the preferred way should be the former.

Let me know.
Regards

**Comment by ValDY69** [comment]
i am using your TextDemo.py with MoveTimed but only one animation in a sequence yes .

i try to add lineType=LINE_AA but i have seen no difference on my Windows simulator.

the problem is the same for me , the text scroll entirely but it begin another cycle during approximatively 0.5 sec before restart again normaly

Regards ,
Valentin

**Comment by BNNorman** [comment]
Just uploaded some fixes for line type – worked ok for me.

 

Ok, there’s a bug in MoveTimed – just saw it happen myself. Will Investigate

**Comment by ValDY69** [comment]
ok Brian i will test it soon , thank you !

I have modified a little your code to work with 64*64 Led Panels ! and it works i can pull request if you want ?

Regards,
Valentin

**Comment by BNNorman** [comment]
I have uploaded a new version of TextAnimations.py – it seems to work ok now – no odd flashes at the end (brief reset)

**Comment by BNNorman** [comment]
What changes were made where  and why? My test panel is 64x64.

**Comment by ValDY69** [comment]
Ok perfect brian !

I was talking about each Led Module 64*64 1/32 scan not the entire screen , I have added "cols" property on options for matrix and modify : 

in Panel.py : 

    #height=Options.rows*Options.parallel
    #width=Options.rows*Options.chain_length

    height=Options.rows*Options.parallel
    width=Options.cols*Options.chain_length

in rgbMatrix.py : 

        #pixelWidth = self.options.cols * self.options.parallel
        #pixelHeight = self.options.rows * self.options.chain_length

        pixelWidth = self.options.cols * self.options.chain_length
        pixelHeight = self.options.rows * self.options.parallel

and for the simulator : 

class RGBMatrixOptions(object):
    rows = 32
    **cols = 32**
    parallel = 2
    chain_length = 2
    gpio_slowdown = 2       # gets rid of flickering leds on my Pi3
    drop_privileges = False # allow images to be loaded

    # a 64x64pixel display on screen is very small so we scale it up
    scale = 10

    # video capture
    videoCapture=False
    videoName="./HUB75 {width}x{height}.avi"

    # misc
    debug=False
    fps=100

    def validate(self):
        assert type(self.parallel) is int, "parallel parameter should be an int."
        assert type(self.rows) is int, "rows parameter should be an int."
        **assert type(self.cols) is int, "cols parameter should be an int."**
        assert type(self.chain_length) is int, "chain_len parameter should be an int."
        assert type(self.gpio_slowdown) is int, "gpio_slowdown parameter should be an int."
        assert type(self.drop_privileges) is bool, "drop_privileges parameter should be a boolean."
        assert type(self.scale) is int, "scale parameter should be an int."
        assert type(self.videoCapture) is bool, "videoCapture parameter should be a boolean."
        assert type(self.videoName) is str, "videoName parameter should be a string."
        assert type(self.fps) is int, "fps parameter should be an int."
        assert type(self.debug) is bool, "debug parameter should be a boolean"

**Comment by BNNorman** [comment]
The values in Panel.py/RGBMatrixOptions.py  are defaults for my panel. They are over ridden by values passed in using Panel.init() which, in turn get passed to RGBMatrix.py (or the HZeller drivers.

 

Thanks for pointing out ‘cols’ – my panels are square so my focus was elsewhere and I forgot about that.  I have amended RGBMatrix.py to use cols which now should be passed in with Panel.Init(…)

 

You didn’t need to change Panel.py if you changed RGBMatrixOptions.py (default values) – The values in Panel.py are a hangover from when I first started writing the code – I have commented them out. And added cols to RGBMatrixOptions.

 

Note the changes are just default values Panel.init(…) can pass in anything it likes valid matrix parameters are extracted. Others, if not needed are ignored.

 

Regards

Brian

**Comment by ValDY69** [comment]
hello brian ,

i have now an error when i test the TextDemo.py : 

*** exception:
Traceback (most recent call last):
  File "TextDemo.py", line 98, in <module>
    A.run()
  File "/home/pi/lib/rpi-rgb-led-matrix-animator/LEDAnimator/Animator.py", line 98, in run
    animInfo.nextFrame(self.debug)
  File "/home/pi/lib/rpi-rgb-led-matrix-animator/LEDAnimator/AnimInfo.py", line 51, in nextFrame
    if self.animFunc.nextFrame(debug=self.debug,id=self.animFunc.id):
  File "/home/pi/lib/rpi-rgb-led-matrix-animator/LEDAnimator/AnimBase.py", line 302, in nextFrame
    self.step()
  File "/home/pi/lib/rpi-rgb-led-matrix-animator/LEDAnimator/TextAnimations.py", line 203, in step
    self.drawText()
  File "/home/pi/lib/rpi-rgb-led-matrix-animator/LEDAnimator/TextAnimBase.py", line 188, in drawText
    self.font.drawText(self.textBuffer,origin,self.text.getText(),self.text.getFgColor(),self.lineType)
TypeError: drawText() takes exactly 5 arguments (6 given)

can you help me ?  i have this error both on simulator and Rpi 

Regards ,
Valentin

**Comment by BNNorman** [comment]
Sounds like one of the files I uploaded hasn’t been updated on your machine  – I added lineType to the end of all  “def drawText()” parameters with default if LINE_8  in these files :-

 

TextAnimBase.py

Font.py

OPENCV/Font.py

BDF/Font.py

 

In order to fix the LINE_AA issue.

 

Check all the def drawText(…) methods and add lineType=LINE_8 if it’s missing (it isn’t used by BDF but needed to be able to avoid messing about with if..else statements

**Comment by BNNorman** [comment]
Might be my fault – may not have pushed LEDAnimator\Font.py – have just pushed it.

**Comment by ValDY69** [comment]
Hello , 
ok now it's fully working for me without any spaces in the string !

i can close this issue.

Thank you brian for your work !

Regards , Valentin

**Comment by BNNorman** [comment]
Glad it’s useful
