### ISSUE TITLE
1px Border at right and bottom of the screen 

### ISSUE THREAD

**Issue by ValDY69** [BNNorman/rpi-rgb-led-matrix-animator#4]
Hello Brian,

I have an 1px border now when playing your Examples in both Simulator and Panels.

Can you please remove this like the previous version ?

Thank you ,

Regards
Valentin

**Comment by BNNorman** [comment]
Is it right hand edge and bottom edge?

 

If so it’s the old problem with calculating the foreground image slice when laid over the background. I would need to do some more work on that if that’s the case. (UtilLib.py)

**Comment by ValDY69** [comment]
Yes right and bottom ,

Yes it is an old problem but was previously already resolved

Thank you brian 

Regards ,
Valentin

**Comment by BNNorman** [comment]
Ok, it crept back in because odd image slice sizes were appearing elsewhere and alphaBlend() was complaining that the slices weren’t the same size which results in the image not getting pasted to the output, so I put back a -1 to correct it

 

You can temporarily resolve it by removing the -1 on these lines from lines 189/190 and 197/198 in UtilLib.py so they look like this:-

    fx1=fx0+fw
    fy1=fy0+fh

 

    bx1=bw
    by1=bh

 

to me the -1 made mathematical sense because pixel numbering is zero based. Removing them the getOverlapSlices() routine returns the size expected.

 

However, there remains a problem in the animation TheMatrix where the bottom line is unaffected by rolling – I’m trying to determine if this is caused by rounding errors when the images are resized (They aren’t  64x64 with a 1:1 aspect ration).

 

I haven’t finished looking at this but right now my central heating is not working (brr) and it’s demanding my attention.

**Comment by BNNorman** [comment]
I have uploaded two fixes. TextAnimations.py and UtilLib.py.

 

Hopefully this solves the 1 pixel gap problem.

**Comment by ValDY69** [comment]
ok i test it and it works again !
Thank you brian 
i close this issue

Regards,
Valentin
