### ISSUE TITLE
Font Problem with special chars

### ISSUE THREAD

**Issue by ValDY69** [BNNorman/rpi-rgb-led-matrix-animator#9]
Hello Brian ,

I have a problem with the two fonts : 

i can't use some specifics chars like :  'é' / 'è' / 'ç' / 'à'  and the most important char that i need the Euros logo '€'

Can you help me ? 
How i can add this missing chars ?

Regards ,
Valentin

**Comment by BNNorman** [comment]
The fonts included were designed before the Euro and created by someone else (see HZeller who included the BDF opensource fonts in his project)

However, I believe openCV can be setup to use other fonts – http://www.codesofinterest.com/2017/07/more-fonts-on-opencv.html - I never looked any deeper because I had no need for it on a low res matrix.

BDF fonts

You would need to look for a BDF font editor (gbdfed - http://sofia.nmsu.edu/~mleisher/Software/gbdfed/) and create your own character and add it to the BDF file (it’s a text file with  a hex bitmap – open one and take a look). 

This might help: https://en.wikipedia.org/wiki/Glyph_Bitmap_Distribution_Format as would the full spec: https://wwwimages2.adobe.com/content/dam/acom/en/.../font/pdfs/5005.BDF_Spec.pdf

You would need to know the ascii code for the characters you add. Here’s the exclamation mark from the 9x18.bdf font note the BBX (bounding box values)

STARTCHAR exclam		<- text description
ENCODING 33		<- ascii code for the exclamation (!) character)
SWIDTH 540 0
DWIDTH 9 0
BBX 9 18 0 -4
BITMAP
0000
0000
0000
0800
0800
0800
0800
0800
0800
0800
0000
0000
0800
0800
0000
0000
0000
0000
ENDCHAR


The font is 9 pixels wide so the bitmap decodes into 16 bits.

0000000000000000
0000000000000000
0000000000000000
0000100000000000
0000100000000000
0000100000000000
0000100000000000
0000100000000000

And so on. 

The beginning of the BDF file says the font ascent is 14 pixels and the descent is 4 (total 18). So your character must sit on the baseline which is 4 pixels from the bottom.

My BDF font renderer just renders all the BDF fonts as monospaced (since DWIDTH is 9 for all the characters.)

Hope that helps.

**Comment by ValDY69** [comment]
ok thank you brian ,

i agree with you that there is no need for other fonts style because of low res of panels but i only need "french specific chars" like 'é' or 'è' but when i define a string with this chars for the OpenCv fonts it is replaced by '?' char it seems that this is a Encoding problem no ?
 can i set the enconding for openCv ?

for the BDF font i can use all the french symbols but not the '€' symbol , i try to download gbdfedbut i don't find any .exe to run ... 
it seems that for BDF fonts i need the ENCODING value for '€' symbol but i don't know him can you help me for this symbol please because it's very important for me 

regards,
Valentin

**Comment by BNNorman** [comment]
This is all about handling unicode characters – which I didn’t factor in.
 
In python 3  the € symbol can be pasted into a text string and it is printed  but python 2 doesn’t like it. None of the python 2 examples on the web worked for me either.

 

Just looked through 9x18.bdf and it does include a Euro symbol as decimal character 8364 so the code needs the handling of Unicode sorting out. However, I struggled to get Python 2 to accept the euro symbol even when including the info here https://www.python.org/dev/peps/pep-0263/

 

The symbol is already in the BDF font file (9x18.bdf for sure) – search for encoding 8364 - I never checked that out before.

 

My BDF.Parser.py reads the whole file in but the problem is getting python to request a character after 255.

 

Quick and dirty workaround: swap the encoding with char 255 then you should be able to include it like so “This is a euro symbol \xff”.

 

As for openCV Hershey fonts – if it’s going to be a problem getting python2 to accept the euro symbol so I don’t know if switching to python 3 would fix it.

 

I’ll add it as an issue.

**Comment by angelogoncalve** [comment]
Use this:

#!/usr/bin/env python
from PIL import Image, ImageDraw, ImageColor, ImageFont
import os
from rgbmatrix import RGBMatrix, RGBMatrixOptions, graphics


class ImageText(object):
    """ Simple wrapper to PIL library, handling text images """

    def __init__(self, font, text, colour):
        self.image = None
        self.font = font
        self.colour = colour
        self.size = None
        #self.__matrix = Matrix()
        self.set_text(text)

    def set_text(self, text):
        """ Set the text size and image """
        self.text = text
        self.set_size()
        self.set_image()

    def set_size(self):
        """ Set text size """
        self.size = self.font.getsize(self.text)
        return self.size

    def set_image(self):
        """ Create an image using the defined text """
        #self.image = Image.fromarray(self, mode="RGB")
        black = ImageColor.getrgb("#000")
        size_image = (self.size[0], self.size[1])
        self.image = Image.new("RGB", size_image, black)
        self.image = self.image.rotate(0)
        draw = ImageDraw.Draw(self.image)
        draw.font = "0"  # No antialias
        draw.text((0, 0), self.text, font=self.font, fill=self.colour)
        return self.image

    def load(self):
        return self.image.load()

    def save(self, image):
        return self.image.save(image)


def get_file(path):
    dir = os.path.dirname(__file__)
    return os.path.join(dir, path)


def load_font(font_text, font_size):
    """ Load the fonts that will be used by the display """
    font_path = get_file('fonts/' + font_text)

    if font_path.endswith(".bdf"):
        font = graphics.Font()
        font.LoadFont(font_path)
        font.CharacterWidth(font_size)
    elif font_path.endswith(".ttf"):
        font = ImageFont.truetype(font_path, font_size)
    elif font_path.endswith(".pil"):
        font = ImageFont.load(font_path)

    return font


number_of_rows = 32
number_of_panels = 2
parallel = 1
number_of_columns = 32

options = RGBMatrixOptions()


def rgbmatrix_options():
    #options = RGBMatrixOptions()
    options.multiplexing = 0
    options.row_address_type = 0
    options.brightness = 100
    options.rows = number_of_rows
    options.cols = number_of_columns
    options.chain_length = number_of_panels
    options.parallel = parallel
    options.hardware_mapping = 'regular'
    options.inverse_colors = False
    options.led_rgb_sequence = "RGB"
    options.gpio_slowdown = 4
    options.pwm_lsb_nanoseconds = 130
    options.show_refresh_rate = 0
    options.disable_hardware_pulsing = True
    options.scan_mode = 1
    options.pwm_bits = 1
    options.daemon = 0
    options.drop_privileges = 0
    return options


options = rgbmatrix_options()
display = RGBMatrix(options=options)


# load font from the OS
font_text = 'pixelmix.ttf'
#font_text = '10x20.bdf'
font_size = 15
font = load_font(font_text, font_size)


# Text to be drawn on the led matrix
data = 'Hello'
__text = data.upper()
# Loads color
colour = (0, 255, 0)
""" Create an image using the defined text """
image = ImageText(font, __text, colour)

(w, h) = .image.size
pix = image.load()

starttime = time.time()
for x in range(w):
     for y in range(h):
          endtime = time.time()
          (r, g, b) = pix[x, y]
          color = (r, g, b)
          #color = image.getpixel((x, y))
          if color != (0, 0, 0):
             display.SetPixel(x, y, r, g, b)
             textspeed = endtime - starttime
            #time.sleep(textspeed)
            refresh_rate = 5.0
            time.sleep(refresh_rate - (textspeed % refresh_rate))

**Comment by BNNorman** [comment]
Thanks, i was looking at PIL. Does this work? How does it handle transparency?

**Comment by angelogoncalve** [comment]
Yes it works Dear Brian.

**Comment by BNNorman** [comment]
Great. I'll take a closer look tomorrow.

**Comment by angelogoncalve** [comment]
Ok good is using the PIL to scroll a text message characters how it is possible and put that in a thread, to be possible kill the thread when is requested another command to put another data in the panel? Thank you for your help and attention my friend.

**Comment by BNNorman** [comment]
How does all this relate to my code? It looks like you are driving the panel directly. To scroll a text image you need to redraw it in its new position after blanking the panel. Use the SwapOnVSync() from the hzeller drivers in your loop. When you have the loop working run it from a thread-see how i do that in the Simulator.Matrix.py script.

**Comment by ValDY69** [comment]
Brian , i test to add # coding=UTF-8 at the top of the file and i have a different behavior 

now i have an exception when i add '€' in a BDF string : 

![image](https://user-images.githubusercontent.com/34503404/36842495-1f345522-1d4c-11e8-9bf9-cbfd0037a7da.png)

and special chars like 'é' is not recognize properly but in ISO8859-15 it was ...

It seems that the encoding is "doing something on Python 2" 
but i don't know why with UTF-8 i can't have the good symbol because , in the Bdf file as you said there are all the specific chars already present

**Comment by BNNorman** [comment]
I think this happens because Unicode characters are stored as two bytes so you need to tell python that.

 

Specify your string as Unicode like this :-

 

bdfText=u"Hello sweetie BDF 12pt text here! €"

 

At the start of the TextDemo.py I added this line (not sure if you were just being brief in your email)

 

# -*- coding: UTF-8 -*-

 

Net result – it worked.

**Comment by BNNorman** [comment]
I agree - a minefield.
Plus, the UTF-8 thing doesn't work with openCV unless it was built with QT support.

**Comment by ValDY69** [comment]
Thank you brian !

For now it's work fully with the BDF font with UTF-8 encoding specify in the pyhton file and with the 'u' before the string

But the problem persist with OpenCV Hershey font ..
I don't understand why the OpenCV font doesn't work in UTF-8 , what is QT support ?
What is the encoding used by OpenCV ?

**Comment by ValDY69** [comment]
i try to add 'u' before the string for Hershey Font too but i have an Exception now : 

![image](https://user-images.githubusercontent.com/34503404/36853384-a82c40ca-1d6e-11e8-8c05-5e5e1a1c4d17.png)

**Comment by BNNorman** [comment]
Do a web search for python Qt (PyQt) – it’s a GUI library. 

 

OpenCV – I’m not sure – just found openCV addText() (openCV 2.4)  which seems to work with fontQt() – not compatible with putText() which is what I am currently using.

 

The example is (C+):-

 

CvFont font = fontQt(''Times'');

addText( img1, ``Hello World !'', Point(50,50), font);

 

I don’t know if there’s a Python interface to addText.

 

I would need to try that (maybe you can) – fontQt() uses the system fonts which may be different on, well, different systems.

**Comment by BNNorman** [comment]
Frustrating isn’t it?

**Comment by ValDY69** [comment]
yes it's Frustrating  :-) and so complicating for me because i don't know pyhton and Qt very well so thank you for all you are doing for me

**Comment by BNNorman** [comment]
Just found this:-

 

To link openCV with to PyQt you need to set the option WITH_QT=ON – I’m not about to recompile my openCV on my Windows PC since, in my experience, things that worked suddenly break.

 

Unfortunately, I still cannot find a python binding to use it. I don’t know if it got into openCV3.

 

It’s still looking like PIL is the way to go but I need to add a Font.py for TrueType and OpenType similar to your code.

**Comment by angelogoncalve** [comment]
Dear Brian. Thank you for your attention my friend. Yes the PIL image is driving the panel directly. The text and the font are transformed to a PIL image and used the methods CreateFrameCanvas() and SwapOnVSync() from HZeller library to scroll a text.

**Comment by BNNorman** [comment]
The code has been added to handle TrueType, OpenType and PIL fonts
